/**
 * DTO FOR TICKET CREATION
 * id and creation_date are generated by the system and should not be provided by the user
 */
export interface CreateTicketDTO {
    code: string;                   // Unique code for the ticket (alphanumeric string)
    service_type: string;           // Type of service associated with the ticket
    status: string;                 // Status: created
}

/**
 * DTO FOR TICKET STATUS UPDATE
 * Update status and expiration_date of a ticket
 */
export interface UpdateTicketStatusDTO {
    status: string;                     // Status: created
    expiration_date: string;            // Date when the ticket expires (null if it has been just created)
}

/**
 * DTO FOR TICKET RETRIEVAL
 */
export interface TicketDTO {
    id: string;                    // Unique identifier for the ticket (uuid)
    code: string;                  // Unique code for the ticket (alphanumeric string)
    service_type: string;          // Type of service associated with the ticket
    status: string;                // Current status of the ticket
    creation_date: string;           // Date when the ticket was created
    expiration_date: string | null;  // Date when the ticket expires (null if it has been just created)
}

